# Generated by Django 3.1.7 on 2021-07-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20210723_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(default='nick.lesho@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ticker',
            field=models.TextField(max_length=6),
        ),
    ]
